### ISSUE TITLE
Are you still planning to open source the dataset?

### ISSUE THREAD

**Issue by ahmadmughees** [sofffty/TCRSF#4]
Are you still planning to open source the dataset?

**Comment by lijfrank-open** [comment]
Updated! The new repository for this work is https://github.com/lijfrank-open/SFCHD-SCALE. Thanks!

**Comment by lijfrank** [comment]
> Are you still planning to open source the dataset?

Updated! The new repository for this work is https://github.com/lijfrank-open/SFCHD-SCALE. Thanks!

**Comment by ahmadmughees** [comment]
Perfect. Thanks.
